[package]
name = "memory-buffer"
version = "0.0.2"
description = "A persistent buffer implementation in motoko."
repository = "https://github.com/NatLabs/memory-buffer"
keywords = [ "region", "buffer", "persistent", "collections", "encoding" ]

[dependencies]
base = "0.10.2"
memory-region = "0.1.0"

[dev-dependencies]
test = "1.0.1"
bench = "1.0.0"